#!/usr/bin/env sh

# Gradle wrapper script generated by Claude
# Uses the existing gradle/wrapper/gradle-wrapper.jar in this project.

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"

if [ -n "$JAVA_HOME" ]; then
  JAVA_EXE="$JAVA_HOME/bin/java"
else
  JAVA_EXE="java"
fi

CLASSPATH="$DIR/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
